### PR TITLE
Feature/51 java11

### PR DESCRIPTION
**Pull request by cwolfes**
Change Jenkins base image to java 11 (see https://github.com/cloudogu/java/tree/v11.0.5-1).

### CODE REVIEW

**Comment by cwolfes** [comment]
@robertauer @ppxl where should the documentation take place? I have created some examples that can help migrating legacy builds.

**Comment by ppxl** [comment]
> @robertauer @ppxl where should the documentation take place? I have created some examples that can help migrating legacy builds.

The notification is a good start but it is not everything, you are totally right there. TBH, this dogu's release note is an extremely good start because it is in the direct vicinity of the code. Also keep in mind that release notes are for humans. In this case for humans that most probably may want to solve exactly this problem.

Another place would be the EcoSystem documentation. But I can't recall if we have a EcoSystem-wide release note mechanism.

Yet another thing is documentation we have already at hands for specific customers. But in the end this documentation is most probably a quintessence of the release notes, so you really should start with those. Make the release note description as short as possible but in a way it is still intelligeble.

**Comment by ppxl** [comment]
Additionally, the current branch conflict should be resolved ;)

**Comment by cwolfes** [comment]
> Additionally, the current branch conflict should be resolved ;)

this happend because i released jenkins in version 2.222.1-1

**Comment by cwolfes** [comment]
> > @robertauer @ppxl where should the documentation take place? I have created some examples that can help migrating legacy builds.
> 
> The notification is a good start but it is not everything, you are totally right there. TBH, this dogu's release note is an extremely good start because it is in the direct vicinity of the code. Also keep in mind that release notes are for humans. In this case for humans that most probably may want to solve exactly this problem.
> 
> Another place would be the EcoSystem documentation. But I can't recall if we have a EcoSystem-wide release note mechanism.
> 
> Yet another thing is documentation we have already at hands for specific customers. But in the end this documentation is most probably a quintessence of the release notes, so you really should start with those. Make the release note description as short as possible but in a way it is still intelligeble.

**Comment by robertauer** [comment]
@cwolfes I added your documentation to the README.md and linked to it from the changelog and upgrade-notification.sh

**Pull request merged**
